// Browser-safe re-export of preset utilities.
// Use `shadcn/preset` for client-side code.
export {
  DEFAULT_PRESET_CONFIG,
  decodePreset,
  encodePreset,
  fromBase62,
  generateRandomConfig,
  generateRandomPreset,
  isPresetCode,
  isValidPreset,
  PRESET_BASE_COLORS,
  PRESET_BASES,
  PRESET_CHART_COLORS,
  PRESET_FONT_HEADINGS,
  PRESET_FONTS,
  PRESET_ICON_LIBRARIES,
  PRESET_MENU_ACCENTS,
  PRESET_MENU_COLORS,
  PRESET_RADII,
  PRESET_STYLES,
  PRESET_THEMES,
  type PresetConfig,
  toBase62,
  V1_CHART_COLOR_MAP,
} from "./preset";
